var product = [{
    "id": 0,
    "title": "",
    "price": "",
    "description": "",
    "brand": "",
    "image": "../COMPARISON/No-Image-Placeholder.png",
}, {
    "id": 1,
    "title": "GUCCI MARMONT",
    "price": "$999",
    "description": "1): White matelass chevron leather. <br> 2): White enamel brass hardware. <br> 3): Cotton linen lining. <br> 4): Magnetic snap closure. <br> 5): Weight: 1.26lbs approximately. <br> 6): Mini size: 7 W x 5.9H x 3.1D .<br> 7): Made in Italy.",
    "brand": "GUCCI",
    "image": "../brand_images/gucci/image1.jpg",
}, {
    "id": 2,
    "title": "GUCCI BLONDIE",
    "price": "$799",
    "description": "1): Light green leather. <br> 2): Cotton linen lining. <br> 3): Round Interlocking G leather patch. <br> 4): Top handle with 3.1 drop. <br> 5): Adjustable shoulder strap with 20.5 drop. <br> 6): Double zipper closure with Round Interlocking G .<br> 7): Made in Italy.",
    "brand": "GUCCI",
    "image": "../brand_images/gucci/image(2.1).jpg",
}, {
    "id": 3,
    "title": "GUCCI BLONDIE SMALL TOTE BAG",
    "price": "$799",
    "description": "1): Black leather. <br> 2): Cotton linen lining. <br> 3): Round Interlocking G leather patch. <br> 4): Inside: 3 main compartments and 1 zip pocket. <br> 5): Top handle with 5.9 drop. <br> 6):Small size: 11.8 W x 9.4 H x 2.4 D.<br> 7): Made in Italy.",
    "brand": "GUCCI",
    "image": "../brand_images/gucci/image(3.1).jpg",
},{
    "id": 4,
    "title": "GUCCI SHOULDER BAG",
    "price": "$1100",
    "description": "1): Light pink soft leather. <br> 2):Shiny gold-toned hardware. <br> 3): Handle: 7 strap drop from central hole, handle wit. <br> 4): Magnetic closure with Double G. <br> 5): Adjustable shoulder strap. <br> 6): Medium size: W15.3 x H15 x D.8.<br> 7): Made in Italy.",
    "brand": "GUCCI",
    "image": "../brand_images/gucci/image(4.1).jpg",
},{
    "id": 5,
    "title": "GUCCI OPHIDIA WALLET",
    "price": "$999",
    "description": "1): Beige/ebony GG Supreme canvas, with brown leather trim. <br> 2): Green and red Web. <br> 3): Antique gold-toned hardware. <br> 4): Double G. <br> 5): Eight card slots and two bill compartments. <br> 6): Eight card slots and two bill compartments.<br> 7): Made in Italy.",
    "brand": "GUCCI",
    "image": "../brand_images/gucci/image(5.1).jpg",
},{
    "id": 6,
    "title": "GUCCI WALLET CUT-OUT",
    "price": "$699",
    "description": "1): Black and grey GG Supreme canvas. <br> 2): Moire lining. <br> 3): Inside: 8 card slots and 2 bill compartments. <br> 4):Open: 8.3 W x 3.5 H. <br> 5): Closed: 4.3 W x 3.5 H. <br> 6): Weight: 0.24lbs approximately.<br> 7): Made in Italy.",
    "brand": "GUCCI",
    "image": "../brand_images/gucci/image(6.1).jpg",
},{
    "id": 7,
    "title": "GUCCI JUMBO GG WALLET",
    "price": "$599",
    "description": "1): Taupe jumbo GG leather. <br> 2): Grey leather trim. <br> 3): Moire lining. <br> 4): Antique gold-toned hardware. <br> 5): Inside: 8 card slots and 2 bill compartments. <br> 6): Weight: 0.7kg approximately.<br> 7): Made in Italy.",
    "brand": "GUCCI",
    "image": "../brand_images/gucci/image(7.1).jpg",
},{
    "id": 8,
    "title": "GUCCI MARMONT LEATHER",
    "price": "$999",
    "description": "1): Forest green leather. <br> 2): Palladium-toned hardware. <br> 3): Double G. <br> 4): Eight card slots and two bill compartments. <br> 5): Made in Italy.",
    "brand": "GUCCI",
    "image": "../brand_images/gucci/image(8.1).jpg",
},{
    "id": 9,
    "title": "Louis Vuitton Capucines BB",
    "price": "$2999",
    "description": "1): White. <br> 2): Shearling and Taurillon-leather trim. <br> 3):Gold-color and enamel hardware. <br> 4): Double carry style: flap inside or outside. <br> 5): Compartmented interior with zipped pocket. <br> 6): Strap: Removable, not adjustable.<br> 7): Made in France, Spain, Italy or in the US.",
    "brand": "Louis Vuitton",
    "image": "../brand_images/Louis Vuitton/image(1).jpg",
},{
    "id": 10,
    "title": "Louis Vuitton Locky BB",
    "price": "$2499",
    "description": "1): Black. <br> 2): Monogram coated canvas and smooth cowhide leather. <br> 3): Smooth cowhide-leather trim. <br> 4): Gold-color hardware. <br> 5): Flat inside pocket. <br> 6): Strap Drop Max.: 59.0 cm.<br> 7): Made in France, Spain, Italy or in the US.",
    "brand": "Louis Vuitton",
    "image": "../brand_images/Louis Vuitton/image(2).jpg",
},{
    "id": 11,
    "title": "Louis Vuitton Twist MM",
    "price": "$1199",
    "description": "1): Camel Light Brown. <br> 2):Epi grained cowhide leather. <br> 3): Epi cowhide-leather trim. <br> 4): Smooth cowhide leather lining. <br> 5): Gold-color hardware. <br> 6): Transforming signature LV Twist lock.<br> 7): Made in France, Spain, Italy or in the US.",
    "brand": "Louis Vuitton",
    "image": "../brand_images/Louis Vuitton/image(3).jpg",
},{
    "id": 12,
    "title": "Louis Vuitton Twist Lock XL",
    "price": "$1999",
    "description": "1): Gold Miel Brown. <br> 2): Epi cowhide leather. <br> 3): Gold-color hardware. <br> 4): Large inside pocket. <br> 5): Flap closure with decorative LV Twist lock (not functional). <br> 6): Strap Drop Max.: 51.5 cm.<br> 7): Made in France, Spain, Italy or in the US.",
    "brand": "Louis Vuitton",
    "image": "../brand_images/Louis Vuitton/image(4).jpg",
},{
    "id": 13,
    "title": "Louis Vuitton Multiple Wallet",
    "price": "$699",
    "description": "1): Cowhide leather. <br> 2): Cowhide-leather trim. <br> 3): 3 card slots. <br> 4): 2 inside pockets. <br> 5): 2 compartments for bills and tickets. <br> 6): 2 side slots for receipts.<br> 7): Made in France, Spain, Italy or in the US.",
    "brand": "Louis Vuitton",
    "image": "../brand_images/Louis Vuitton/image(5).jpg",
},{
    "id": 14,
    "title": "Louis Vuitton Multiple Wallet2",
    "price": "$999",
    "description": "1): Optic White. <br> 2): Monogram coated canvas and Taiga cowhide leather. <br> 3): Cowhide-leather lining. <br> 4): Palladium-color hardware. <br> 5): 3 card slots. <br> 6): 2 inside pockets.<br> 7): Made in France, Spain, Italy or in the US.",
    "brand": "Louis Vuitton",
    "image": "../brand_images/Louis Vuitton/image(6).jpg",
},{
    "id": 15,
    "title": "Louis Vuitton Slender Wallet",
    "price": "$899",
    "description": "1): Blue Sapphire. <br> 2): Damier Infini cowhide leather and Damier Graphite coated canvas. <br> 3): Cowhide-leather lining. <br> 4): 8 card slots. <br> 5): 3 card slots. <br> 6): Bill compartment.<br> 7): Made in France, Spain, Italy or in the US.",
    "brand": "Louis Vuitton",
    "image": "../brand_images/Louis Vuitton/image(7).jpg",
},{
    "id": 16,
    "title": "Louis Vuitton Brazza Wallet",
    "price": "$1190",
    "description": "1): Navy Blue. <br> 2): LV Aerogram cowhide leather. <br> 3):Signature initials in tone-on-tone metal. <br> 4): 16 credit card slots. <br> 5): ID or business card slot. <br> 6): 4 inside flat compartments for bills and tickets.<br> 7): Made in France, Spain, Italy or in the US.",
    "brand": "Louis Vuitton",
    "image": "../brand_images/Louis Vuitton/image(8).jpg",
},{
    "id": 17,
    "title": "Alexander The Peak Bag ",
    "price": "$2000",
    "description": "1): Strap drop: 30 cm / 11.8 inches. <br> 2): Dimensions: 28 x 20 x 11 cm / 11 x 7.8 x 4.3 inches. <br> 3): 100% Calf Leather. <br> 4): Magnetic fastening. <br> 5): Fixed chain strap. <br> 6): Brass hardware with antique silver finishing.<br> 7): Contrasting suede lining.",
    "brand": "Alexander McQueen",
    "image": "../brand_images/Alexander/imagea(1).jpg",
},{
    "id": 18,
    "title": "Alexander The Jewelled Hobo ",
    "price": "$2200",
    "description": "1): Dimensions: 20 x 12 x 8 cm / 7.8 x 4.7 x 3.1 inches. <br> 2): 100% Calf Leather. <br> 3):  Silver-finished handle adorned with Swarovski-encrusted rings. <br> 4): Magnetic fastening. <br> 5): Detachable chain strap. <br> 6): Brass hardware with antique silver finishing.<br> 7): Leather lining.",
    "brand": "Alexander McQueen",
    "image": "../brand_images/Alexander/imagea(2).jpg",
},{
    "id": 19,
    "title": "Alexander  Mini Jewelled Satchel ",
    "price": "$1500",
    "description": "1): Dimensions: 17.5 x 9.5 x 4cm / 6.8 x 3.7 x 1.5 inches. <br> 2): Strap drop: 55cm / 21.6 inches. <br> 3): 100% Calf Leather. <br> 4): Silver four-ring embellishment encrusted with Swarovski crystals. <br> 5): One main compartment and one card slot. <br> 6): Adjustable leather and chain strap.<br> 7): Brass hardware with antique silver finishing.",
    "brand": "Alexander McQueen",
    "image": "../brand_images/Alexander/imagea(3).jpg",
},{
    "id": 20,
    "title": "Alexander The Jewelled Hobo Mini Bag ",
    "price": "$2500",
    "description": "1): Dimensions: 20 x 12 x 8 cm / 7.8 x 4.7 x 3.1 inches. <br> 2): Strap drop: 52 cm / 20.4 inches. <br> 3): 100% Calf Leather. <br> 4): Magnetic fastening. <br> 5): Detachable chain strap. <br> 6): Tonal lining.<br> 7): Brass hardware with antique silver finishing.",
    "brand": "Alexander McQueen",
    "image": "../brand_images/Alexander/imagea(4).jpg",
},{
    "id": 21,
    "title": "Alexander Leather Billfold Wallet",
    "price": "$499",
    "description": "1): 100% Mutton Sking. <br> 2): Dimensions: 11 x 10 x 1,5 cm / 4.3 x 3.9 x 0.5 inches. <br> 3): Black soft lambskin billfold wallet. <br> 4): 8-slot card compartment and notes section.",
    "brand": "Alexander McQueen",
    "image": "../brand_images/Alexander/imagea(5).jpg",
},{
    "id": 22,
    "title": "Alexander The Harness Billfold Wallet",
    "price": "$599",
    "description": "1): Multicoloured calf leather billfold wallet featuring. <br> 2): all-over Watercolour Graffiti print and black harness detailing. <br> 3): 100% Calf Leather. <br> 4): The wallet has eight card slots, two flat pockets and two bill compartments.<br> 5): Finished with an Alexander McQueen signature.",
    "brand": "Alexander McQueen",
    "image": "../brand_images/Alexander/imagea(6).jpg",
},{
    "id": 23,
    "title": "Alexander Brushstroke Billfold Wallet",
    "price": "$299",
    "description": "1): Dimensions: 11.5 x 9.5 x 1.5cm / 4.5 x 3.7 x 0.5 inches. <br> 2): Black and white leather billfold wallet featuring. <br> 3): 100% Calf Leather. <br> 4): all-over Brushstroke print.<br> 5): Black and white leather billfold wallet featuring. <br> 6): all-over Brushstroke print <br> 7): Lined with contrasting spring blue leather. Alexander McQueen tonal signature",
    "brand": "Alexander McQueen",
    "image": "../brand_images/Alexander/imagea(7).jpg",
},{
    "id": 24,
    "title": "Alexander Studded Leather Pocket",
    "price": "$599",
    "description": "1): Dimensions: 7 x 11 x 0,8 cm / 2.7 x 4.3 x 0.3 inches. <br> 2): Black calf leather pocket organizer with an exploded skull made of hammered studs. <br> 3): 100% Calf skin. <br> 4): Two bill compartments.<br> 5): It features three credit card slots and three flat pockets. <br> 6): White printed Alexander McQueen signature on the front",
    "brand": "Alexander McQueen",
    "image": "../brand_images/Alexander/imagea(8).jpg",
}
];